ktor:
  # This section tells Ktor which function to run on startup.
  application:
    modules:
      - com.example.ApplicationKt.module

  deployment:
    port: ${PORT:9696}

jwt:
  issuer: ${JWT_ISSUER:http://0.0.0.0:9696}
  audience: "users"
  realm: "ktor sample app"
  secret: ${JWT_SECRET:local-dev-secret}

db:
  driver: org.postgresql.Driver
  url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/notes_db}
  user: ${DB_USER:ktor_user}
  password: ${DB_PASSWORD:Kumar@1234}