ktor:
  deployment:
    port: ${PORT} # Use the port Render provides

jwt:
  issuer: "https://your-app-name.onrender.com" # Use your actual Render URL
  audience: "users"
  realm: "ktor sample app"
  secret: ${JWT_SECRET} # <-- CRITICAL: Read secret from environment

db:
  url: ${DATABASE_URL} # <-- CRITICAL: Read database URL from environment
  user: ${DB_USER}
  password: ${DB_PASSWORD}